## What is Pandas.

It is a fast, flexible, power full open source library for data analysis and data manupulation.
You can do any kind of analysis using pandas.

### Pandas have two objects:
1. Pandas series
2. DataFrame Pandas

### Pandas Series
Pandas series is like a columns in a table. It is 1D array holding data of any type.

In [130]:
import numpy as np
import pandas as pd

In [131]:
# Create a list of array ( countries list)

country = ['Pakistan', 'India','Nepal','USA','Afghanistan','Italy']

In [132]:
# Make series of countries

In [133]:
pd.Series(country)

0       Pakistan
1          India
2          Nepal
3            USA
4    Afghanistan
5          Italy
dtype: object

In [134]:
# dtype = object ( Means that pandas called string as object datatype)

In [135]:
runs = [1,3,65,45,76,356]

In [136]:
pd.Series(runs)

0      1
1      3
2     65
3     45
4     76
5    356
dtype: int64

In [137]:
# Index is starting from 0, we can give our own index

In [138]:
# Custom index

marks = [45,32,54,75,86]
subjects = ['Maths', 'Science', 'Urdu', 'computer', 'Physics']

In [139]:
pd.Series(marks, index=subjects)

Maths       45
Science     32
Urdu        54
computer    75
Physics     86
dtype: int64

In [140]:
pd.Series(marks, index=subjects, name='Mine marks')

Maths       45
Science     32
Urdu        54
computer    75
Physics     86
Name: Mine marks, dtype: int64

In [141]:
marks = pd.Series(marks, index=subjects, name='Mine marks')

In [142]:
marks

Maths       45
Science     32
Urdu        54
computer    75
Physics     86
Name: Mine marks, dtype: int64

### Making series using dict

In [143]:
marks = {
    'maths':63,
    'Physics':83,
    'Computer':76,
    'Urdu':99
}

In [144]:
marks

{'maths': 63, 'Physics': 83, 'Computer': 76, 'Urdu': 99}

In [145]:
marks_series = pd.Series(marks, name='Bilal Ramzan')

In [146]:
marks_series

maths       63
Physics     83
Computer    76
Urdu        99
Name: Bilal Ramzan, dtype: int64

### Series Attributes

In [147]:
marks_series.size

4

In [148]:
marks_series.dtype

dtype('int64')

In [149]:
marks_series.name

'Bilal Ramzan'

In [150]:
marks_series.is_unique

True

In [151]:
marks_series.index

Index(['maths', 'Physics', 'Computer', 'Urdu'], dtype='object')

In [152]:
marks_series.values

array([63, 83, 76, 99])

In [153]:
## Series using existing data set ( CSV)

In [154]:
df = pd.read_csv('Datasets/subs.csv')

In [155]:
df

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [156]:
type(df)

pandas.core.frame.DataFrame

In [157]:
# By default the data is stored in DataFrame (Convert it into series.

In [158]:
df = pd.read_csv('Datasets/subs.csv').squeeze()

In [159]:
type(df)

pandas.core.series.Series

In [160]:
df

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [161]:
vk = pd.read_csv('Datasets/kohli_ipl.csv', index_col='match_no').squeeze()

In [162]:
type(vk)

pandas.core.series.Series

In [163]:
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [164]:
b = pd.read_csv('Datasets/bollywood.csv', index_col='movie')

In [165]:
type(b)

pandas.core.frame.DataFrame

In [166]:
b = pd.read_csv('Datasets/bollywood.csv', index_col='movie').squeeze()

In [167]:
type(b)

pandas.core.series.Series

### Imp Series Methods

#### 1. Head and tail method
give the first and last parts of data

In [168]:
b.head()

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
Name: lead, dtype: object

In [169]:
b.tail()

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [170]:
b.sample(5)

movie
Singh Is Kinng                  Akshay Kumar
Munna Bhai M.B.B.S.              Sanjay Dutt
My Bollywood Bride               Jason Lewis
Laila Majnu (2018 film)       Avinash Tiwary
Hawaa Hawaai               Makrand Deshpande
Name: lead, dtype: object

### Value_counts
tells the frequency rate/count (How much time the values come in the data)

In [171]:
b.value_counts()

lead
Akshay Kumar          48
Amitabh Bachchan      45
Ajay Devgn            38
Salman Khan           31
Sanjay Dutt           26
                      ..
Talha Arshad Reshi     1
Garima Agarwal         1
Rasika Agashe          1
Zaheer Iqbal           1
Deepika Amin           1
Name: count, Length: 566, dtype: int64

### Sort_values 
sort all the values

In [172]:
b.sort_values()

movie
Qaidi Band                            Aadar Jain
Roar: Tigers of the Sundarbans      Aadil Chahal
Lipstick Under My Burkha            Aahana Kumra
Raat Gayi Baat Gayi?                Aamir Bashir
Talaash: The Answer Lies Within       Aamir Khan
                                        ...
Dil Toh Deewana Hai                  Zeenat Aman
Sallu Ki Shaadi                      Zeenat Aman
Strings of Passion                   Zeenat Aman
Dunno Y... Na Jaane Kyon             Zeenat Aman
Taj Mahal: An Eternal Love Story     Zulfi Sayed
Name: lead, Length: 1500, dtype: object

In [201]:
b.mode()

0    Akshay Kumar
Name: lead, dtype: object

In [173]:
vk = pd.read_csv('Datasets/kohli_ipl.csv', index_col='match_no').squeeze()

In [174]:
vk.sort_values(ascending=False).head().values[0]

np.int64(113)

In [177]:
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [176]:
# vk.sort_values(inplace=True)

In [178]:
b

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [183]:
# Sort indexing ( As index is movies name, the moavies name sorted from numbers then A-Z)
b.sort_index()

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: object

b.sort_values()

### Series math methods
- count missing values as well

In [188]:
# count missing values as well
vk.count()

np.int64(215)

In [190]:
# Do not count missing values
vk.size

215

In [193]:
subs = pd.read_csv('Datasets/subs.csv')

In [194]:
subs.count()

Subscribers gained    365
dtype: int64

In [195]:
subs.sum()

Subscribers gained    49510
dtype: int64

In [196]:
subs.mean()

Subscribers gained    135.643836
dtype: float64

In [197]:
subs.min()

Subscribers gained    33
dtype: int64

In [198]:
subs.max()

Subscribers gained    396
dtype: int64

In [199]:
subs.median()

Subscribers gained    123.0
dtype: float64

In [202]:
# Most value comes in the data
subs.mode()

   Subscribers gained
0                 105

In [204]:
b.mode()

0    Akshay Kumar
Name: lead, dtype: object

In [205]:
subs.std()

Subscribers gained    62.675023
dtype: float64

In [206]:
vk.var()

688.0024777222344

In [207]:
vk.describe()

count    215.000000
mean      30.855814
std       26.229801
min        0.000000
25%        9.000000
50%       24.000000
75%       48.000000
max      113.000000
Name: runs, dtype: float64

In [208]:
vk.info()

<class 'pandas.core.series.Series'>
Index: 215 entries, 1 to 215
Series name: runs
Non-Null Count  Dtype
--------------  -----
215 non-null    int64
dtypes: int64(1)
memory usage: 3.4 KB

In [217]:
subs.describe()

       Subscribers gained
count          365.000000
mean           135.643836
std             62.675023
min             33.000000
25%             88.000000
50%            123.000000
75%            177.000000
max            396.000000

### Series indexing

In [224]:
# Seies only work on positive indexing
x = pd.Series([1,2,4,5,3,5,7,7654,23])

In [226]:
x

0       1
1       2
2       4
3       5
4       3
5       5
6       7
7    7654
8      23
dtype: int64

In [227]:
x[5]

np.int64(5)